# SPDX-FileCopyrightText: 2026 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    uses: telekom/pubsub-horizon-ci/.github/workflows/gradle-build.yml@91325983ed4f824c569b6dfc349a0cbb2024bb31
    with:
      java-version: "21"
      init-gradle-path: ".github/assets/init.gradle"

  reuse:
    uses: telekom/pubsub-horizon-ci/.github/workflows/reuse-compliance.yml@main

  codeql:
    permissions:
      contents: read
      security-events: write
    uses: telekom/pubsub-horizon-ci/.github/workflows/codeql.yml@main
    with:
      languages: '["java-kotlin","actions"]'
