# SPDX-FileCopyrightText: 2026 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    uses: telekom/pubsub-horizon-ci/.github/workflows/gradle-build.yml@main
    with:
      java-version: "21"
      init-gradle-path: ".github/assets/init.gradle"

  reuse:
    uses: telekom/pubsub-horizon-ci/.github/workflows/reuse-compliance.yml@main

  codeql:
    permissions:
      contents: read
      security-events: write
    uses: telekom/pubsub-horizon-ci/.github/workflows/codeql.yml@main
    with:
      languages: '["java-kotlin","actions"]'

  publish:
    if: github.event_name == 'push'
    needs: [build]
    uses: telekom/pubsub-horizon-ci/.github/workflows/docker-publish.yml@main
    with:
      component: pulsar
      language: java
      init-gradle-path: ".github/assets/init.gradle"
      build-args: "DOCKER_BASE_IMAGE=artifactory.devops.telekom.de/tardis-oci-local/tardis/infra/build/pandora-java-21:1.0.0"
    secrets:
      REGISTRY_USERNAME: ${{ secrets.ARTIFACTORY_O28M_PUSH_USER }}
      REGISTRY_PASSWORD: ${{ secrets.ARTIFACTORY_O28M_PUSH_TOKEN }}
